[package]
name = "small-rust-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
nix = { version = "0.26", default_features = false, features = ["hostname"] }
rand = { version = "0.8", default_features = false, features = [
    "std",
    "std_rng",
    "small_rng",
] }
